//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business__tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Business__tbl()
        {
            this.Schedule_tbl = new HashSet<Schedule_tbl>();
            this.BusinessOpeningHours_tbl = new HashSet<BusinessOpeningHours_tbl>();
        }
    
        public int BusinessCode { get; set; }
        public Nullable<int> CategoryCode { get; set; }
        public string BusinessOwnerCode { get; set; }
        public string BusinessName { get; set; }
        public string FullAddress { get; set; }
        public string Phone { get; set; }
        public string BusinessDescription { get; set; }
    
        public virtual Category__tbl Category__tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule_tbl> Schedule_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessOpeningHours_tbl> BusinessOpeningHours_tbl { get; set; }
    }
}
