//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events__tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Events__tbl()
        {
            this.Schedule_tbl = new HashSet<Schedule_tbl>();
        }
    
        public int EventCode { get; set; }
        public Nullable<int> UserCode { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<bool> GroomOrBride { get; set; }
    
        public virtual Users__tbl Users__tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule_tbl> Schedule_tbl { get; set; }
    }
}
