//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule_tbl
    {
        public int ScheduleCode { get; set; }
        public Nullable<int> EventCode { get; set; }
        public Nullable<int> BusinessCode { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<bool> Done { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<System.TimeSpan> Hour { get; set; }
        public string Description { get; set; }
        public string Subject { get; set; }
        public string ScheduleId { get; set; }
    
        public virtual Business__tbl Business__tbl { get; set; }
        public virtual Events__tbl Events__tbl { get; set; }
    }
}
